# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: API Garage
email: cpatel@apigarage.com
description: Master API workflows and toolset
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://apigarage.com"
twitter_username: apigarage
github_username:  apigarage

# Build settings
markdown: kramdown
